version: "3.9"

services:
  postgres:
    container_name: "postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - ./.data:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - web
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  client-web:
    container_name: "client-web"

    user: node
    image: node:16
    command: "npm run dev"
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/srv/client-web
    env_file:
      - .env
    working_dir: /srv/client-web
    depends_on:
      - postgres
    networks:
      - web

volumes:
  redis-data:
  redis-conf:

networks:
  web:
    external: true
