version: "3.9"

services:
  postgres:
    container_name: "home-inventory-postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - ./.data:/var/lib/postgresql/data

  client-web:
    container_name: "home-inventory-web"
    user: node
    image: node:18
    command: "npm run dev"
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/srv/client-web
    env_file:
      - .env
    working_dir: /srv/client-web
    depends_on:
      - postgres
    networks:
      - web

volumes:
  redis-data:
  redis-conf:

networks:
  web:
    external: true
