version: "3.9"

services:
  postgres:
    container_name: "home-inventory-postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - ./.data:/var/lib/postgresql/data

  web:
    container_name: "home-inventory-web"
    image: node:18
    command: "npm run start"
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/srv/web
    working_dir: /srv/web
    depends_on:
      - postgres
    networks:
      - web
    env_file:
      - .env

networks:
  web:
    external: true
