name: Check TS build (api & web)

on: [push, pull_request]

jobs:
  tsc-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma types
        run: npx prisma generate

      - name: Run yarn turbo run test-tsc
        run: npm run test-tsc
